package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import com.fasterxml.jackson.databind.ObjectMapper;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fern' at '15/03/16 20:26' with Gradle 2.11
 *
 * @author fern, @date 15/03/16 20:26
 */
@SpringBootApplication
public class Library {

    public static void main(String[] args) {
        SpringApplication.run(Library.class, args);
    }
	@Autowired(required = true)
	public void configeJackson(ObjectMapper objectMapper) {
		objectMapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY)
			.setVisibility(PropertyAccessor.CREATOR, Visibility.NONE)
			.setVisibility(PropertyAccessor.GETTER, Visibility.NONE)
			.setVisibility(PropertyAccessor.IS_GETTER, Visibility.NONE)
			.setVisibility(PropertyAccessor.SETTER, Visibility.NONE);
	}
}